// Code generated by gen-matrix DO NOT EDIT.
package geom

type matrix4x4 [4][4]float64

func (m *matrix4x4) determinant() float64 {
	r := 0.
	for i, v := range m[0] {
		r += v * m.cofactor(0, i)
	}
	return r
}

func (m *matrix4x4) cofactor(row, column int) float64 {
	return m.minor(row, column) * sign(row, column)
}

func (m *matrix4x4) minor(row, column int) float64 {
	return m.submatrix(row, column).determinant()
}

func (m *matrix4x4) submatrix(row, column int) *matrix3x3 {
	r := &matrix3x3{}
	for ri, mi := 0, 0; mi < 4; mi++ {
		if mi == row {
			continue
		}
		for rj, mj := 0, 0; mj < 4; mj++ {
			if mj == column {
				continue
			}
			r[ri][rj] = m[mi][mj]
			rj++
		}
		ri++
	}
	return r
}

func (m *matrix4x4) inverse() *matrix4x4 {
	determinant := m.determinant()
	inverse := &matrix4x4{}
	for i := 0; i < 4; i++ {
		for j := 0; j < 4; j++ {
			inverse[j][i] = m.cofactor(i, j) / determinant
		}
	}
	return inverse
}


