// Code generated by gen-matrix DO NOT EDIT.
package geom

type matrix3x3 [3][3]float64

func (m *matrix3x3) determinant() float64 {
	r := 0.
	for i, v := range m[0] {
		r += v * m.cofactor(0, i)
	}
	return r
}

func (m *matrix3x3) cofactor(row, column int) float64 {
	return m.minor(row, column) * sign(row, column)
}

func (m *matrix3x3) minor(row, column int) float64 {
	return m.submatrix(row, column).determinant()
}

func (m *matrix3x3) submatrix(row, column int) *matrix2x2 {
	r := &matrix2x2{}
	for ri, mi := 0, 0; mi < 3; mi++ {
		if mi == row {
			continue
		}
		for rj, mj := 0, 0; mj < 3; mj++ {
			if mj == column {
				continue
			}
			r[ri][rj] = m[mi][mj]
			rj++
		}
		ri++
	}
	return r
}

